<?php

/**
 * @file
 * FAQ module install file.
 */

use Drupal\Core\Field\FieldPurger;
use Drupal\node\Entity\Node;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_schema().
 */
function faq_schema() {
  $schema = [];
  $schema['faq_weights'] = [
    'description' => 'A table containing the weight of each faq node by category.',
    'fields' => [
      'tid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The primary identifier for a term or category.  This will be 0 for non-categorized nodes.',
      ],
      'nid' => [
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
        'default' => 0,
        'description' => 'The primary identifier for a node.',
      ],
      'weight' => [
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
        'description' => 'A number representing the weight of a node.  Nodes with lower weight values will appear above those with higher weight values.',
      ],
    ],
    'primary key' => ['nid', 'tid'],
  ];
  return $schema;
}

/**
 * Implements hook_install().
 */
function faq_install() {
  $locked = Drupal::state()->get('node.type.locked');
  $locked['faq'] = 'faq';
  Drupal::state()->set('node.type.locked', $locked);
}

/**
 * Implements hook_uninstall().
 */
function faq_uninstall() {
  $info = NodeType::load('faq');
  if ($info) {
    $info->delete();
    /** @var \Drupal\Core\Field\FieldPurger $field_purger */
    $field_purger = \Drupal::service(FieldPurger::class);
    $field_purger->purgeBatch(500);
    $nids = \Drupal::entityQuery('node')
      ->condition('type', 'faq')
      ->accessCheck(FALSE)
      ->execute();
    foreach ($nids as $nid) {
      $faqNode = Node::load($nid);
      $faqNode->delete();
    }
  }
}
