<?php

/**
 * @file
 * Contains varbase_faqs.module.
 */

/**
 * Implements hook_page_attachments().
 */
function varbase_faqs_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'varbase_faqs/faq-styles';
}

/**
 * Implements hook_theme().
 */
function varbase_faqs_theme() {
  return [
    'faq_hide_answer' => [
      'template' => 'faq-hide-answer',
      'variables' => ['data' => NULL],
    ],
  ];
}
